version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  backend:
    build: ./node-express-server
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    build: ./react-client
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8081:8081"